# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/micro/go-config"
  version = "0.8.0"

[[constraint]]
  name = "github.com/olivere/elastic"
  version = "6.2.5"

[[constraint]]
  name = "github.com/gorilla/sessions"
  version = "1.1.1"

[[constraint]]
  branch = "master"
  name = "github.com/michaeljs1990/sqlitestore"

[[constraint]]
  branch = "master"
  name = "github.com/wader/gormstore"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.1"

[[constraint]]
  name = "github.com/sendgrid/sendgrid-go"
  version = "3.4.1"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.15.30"

[[constraint]]
  name = "github.com/SparkPost/gosparkpost"
  version = "0.1.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "go.mongodb.org/mongo-driver"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.14.1"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"

[[constraint]]
  name = "github.com/pkg/sftp"
  version = "1.8.3"

[[constraint]]
  name = "github.com/googollee/go-socket.io"
  version = "1.4.1"

[[constraint]]
  name = "gopkg.in/rethinkdb/rethinkdb-go.v5"
  version = "5.0.1"