# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.12

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/markdicksonjr/nibbler
    steps:
      - checkout

      - run: go get github.com/Azure/azure-storage-blob-go/azblob
      - run: go get github.com/SparkPost/gosparkpost
      - run: go get github.com/aws/aws-sdk-go/aws
      - run: go get github.com/aws/aws-sdk-go/aws/credentials
      - run: go get github.com/aws/aws-sdk-go/aws/session
      - run: go get github.com/aws/aws-sdk-go/service/s3
      - run: go get github.com/go-redis/redis
      - run: go get github.com/google/uuid
      - run: go get github.com/googollee/go-socket.io
      - run: go get github.com/gorilla/mux
      - run: go get github.com/gorilla/sessions
      - run: go get github.com/jinzhu/gorm
      - run: go get github.com/jinzhu/gorm/dialects/postgres
      - run: go get github.com/jinzhu/gorm/dialects/sqlite
      - run: go get github.com/keighl/mandrill
      - run: go get github.com/lib/pq
      - run: go get github.com/michaeljs1990/sqlitestore
      - run: go get github.com/micro/go-config
      - run: go get github.com/micro/go-config/source
      - run: go get github.com/micro/go-config/source/env
      - run: go get github.com/micro/go-config/source/file
      - run: go get go.mongodb.org/mongo-driver/mongo
      - run: go get github.com/olivere/elastic
      - run: go get github.com/pkg/errors
      - run: go get github.com/pkg/sftp
      - run: go get github.com/sendgrid/sendgrid-go
      - run: go get github.com/sendgrid/sendgrid-go/helpers/mail
      - run: go get github.com/wader/gormstore
      - run: go get golang.org/x/crypto/bcrypt
      - run: go get golang.org/x/crypto/ssh
      - run: go get golang.org/x/net/context
      - run: go get golang.org/x/oauth2
      - run: go get golang.org/x/oauth2/google
      - run: go get google.golang.org/api/drive/v3
      - run: go get -v -t -d ./...
      - run: go test -v ./...      #- run: go test -v ./...